[package]
name = "compositor"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "homescreen"]
exclude = ["vendor"]

[features]
default = ["session", "backend-udev", "backend-winit"]
# Clipboard, lock, foreign-toplevel, IME, vkbd, idle, output-power, activation.
session = []
backend-udev = []
backend-winit = []

[dependencies.smithay]
git = "https://github.com/mecha-org/smithay"
rev = "60aafc2b1a64395bd32ec93f41e6712a07544c34"
default-features = false
features = [
  "backend_winit",
  "backend_drm",
  "backend_gbm",
  "backend_egl",
  "backend_udev",
  "backend_session_libseat",
  "backend_libinput",
  "renderer_gl",
  "desktop",
  "wayland_frontend",
]

[dependencies.smithay-drm-extras]
git = "https://github.com/mecha-org/smithay"
rev = "60aafc2b1a64395bd32ec93f41e6712a07544c34"
default-features = false

[dependencies]
thiserror = "2.0.20"
tracing = "0.1"
xcursor = "0.3.11"
