[package]
name = "homescreen"
version = "0.1.0"
edition = "2024"

[dependencies]
compositor = { path = "..", default-features = false }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
libc = "0.2"
app = { path = "../vendor/mecha-wayland/crates/app" }
io-ring = { path = "../vendor/mecha-wayland/crates/io-ring" }
wayland = { path = "../vendor/mecha-wayland/crates/wayland", features = ["client"] }
renderer = { path = "../vendor/mecha-wayland/crates/renderer" }
animation = { path = "../vendor/mecha-wayland/crates/animation" }
timer = { path = "../vendor/mecha-wayland/crates/timer" }
window-manager = { path = "../vendor/mecha-wayland/crates/window-manager" }
ui = { path = "../vendor/mecha-wayland/crates/ui" }
khronos-egl = { version = "6", features = ["dynamic"] }
glow = "0.17"
io-uring = "0.7"

[dependencies.smithay]
git = "https://github.com/mecha-org/smithay"
rev = "60aafc2b1a64395bd32ec93f41e6712a07544c34"
default-features = false
features = [
  "backend_egl",
  "renderer_gl",
  "desktop",
  "wayland_frontend",
]
